repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: doppler-compose\.yml
      - id: check-added-large-files
      - id: check-merge-conflict

  # - repo: https://github.com/TekWizely/pre-commit-golang
  #   rev: v1.0.0-rc.1
  #   hooks:
  #     - id: go-staticcheck-pkg
  #       files: ^backend/.*\.go$

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args:
          - --skip=**/package-lock.json,package-lock.json,**/CoverSelector.tsx,**/client.ts,frontend/coverage/**

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.2
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [pre-push]
        args: ['--rev-range', 'HEAD~1..HEAD']
