#  ┌────────────────────────────────────────────────────────────────────────────────────┐
#  │ Purpose:                                                                           │
#  │ - Triggers workflow for deployment to staging                                      │
#  │ - Send a message on PR - to confirm deployment to user                             │
#  └────────────────────────────────────────────────────────────────────────────────────┘
name: 1 - Deploy to Staging

# Enforces Staging branch = staging env
on:
  workflow_dispatch: # manual run fallback
  push:
    branches:
      - staging

# Permissions to write on PR
permissions: write-all

jobs:
  create-release-pr:
    name: Create Release PR (conditional)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches

      - name: Check for Release PR
        id: check-pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Define
          EXISTS=$(gh pr list --base main --head staging --state open --json number --jq 'length')
          echo "exists=$EXISTS" >> $GITHUB_OUTPUT

          # Determine
          if [ "$EXISTS" != "0" ]; then
            echo "::notice::Release PR already exists. Skipping creation."
          else
            echo "::notice::No Release PR exists. Creating one now."
          fi

      - name: Grab Latest Merged PR Info
        if: steps.check-pr.outputs.exists == '0'
        id: get-pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get latest merged PR from staging
          PR_DATA=$(gh pr list --base staging --state merged --limit 1 --json number,title,body,author --jq '.[0]')

          # Extract PR info
          title=$(echo "$PR_DATA" | jq -r '.title')
          body=$(echo "$PR_DATA" | jq -r '.body')
          author=$(echo "$PR_DATA" | jq -r '.author.login')

          # Set outputs for the next step - w/ multiline support
          {
            echo "title<<EOF"
            echo "$title"
            echo "EOF"

            echo "body<<EOF"
            echo "$body"
            echo "EOF"

            echo "author<<EOF"
            echo "$author"
            echo "EOF"
          } >> $GITHUB_OUTPUT


      - name: Create Pull Request
        if: steps.check-pr.outputs.exists == '0'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: staging
          title: ${{ steps.get-pr.outputs.title }}
          body: |
            ## Release PR

            This PR releases changes from staging to production.

            ### Original PR Details:
            ${{ steps.get-pr.outputs.body }}
          labels: release
          assignees: ${{ steps.get-pr.outputs.author }}

  build:
    name: Build Staging
    needs: create-release-pr
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@main
        with:
          lfs: true

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@master

      - name: Fetch Doppler Secrets
        id: doppler
        uses: dopplerhq/secrets-fetch-action@main
        with:
          doppler-token: ${{ secrets.STG_DOPPLER_TOKEN }}
          inject-env-vars: true

      - name: Set versioning - via PR number
        id: version
        env:
          DOPPLER_TOKEN: ${{ secrets.STG_DOPPLER_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the PR Number
          PR_NUM=$(gh pr view --json number -q .number)

          if [ -z "$PR_NUM" ]; then
            echo "ERROR: PR number for this commit is null. See Logs."
            exit 1
          fi

          # Set the version
          export semantic_version=pr-$PR_NUM

          # Update version on Doppler
          doppler secrets set SEMANTIC_VERSION=$semantic_version

          # pass var to other steps
          echo "semantic_version=pr-$PR_NUM" >> $GITHUB_OUTPUT

      - name: Confirm new release (fail-catch)
        if: steps.version.outputs.semantic_version == '' # null
        uses: actions/github-script@main
        with:
          script: |
            core.setFailed("Semantic version is null. See logs.")

      - name: Backend - Build & Push image
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/note-app-backend
          IMAGE_TAG: ${{ steps.version.outputs.semantic_version }} # Since it was changed post-fetch
        run: |
          encore build docker $IMAGE_NAME:$IMAGE_TAG --config encore.prod.json
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Frontend - Build & Push image
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/note-app-frontend
          IMAGE_TAG: ${{ steps.version.outputs.semantic_version }} # Since it was changed post-fetch
        uses: docker/build-push-action@v4
        with:
          context: frontend
          push: true
          tags: $IMAGE_NAME:$IMAGE_TAG
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

  deploy:
    name: Deploy Staging
    needs: build
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Doppler Secrets
        id: doppler
        uses: dopplerhq/secrets-fetch-action@main
        with:
          doppler-token: ${{ secrets.STG_DOPPLER_TOKEN }}
          inject-env-vars: true

      - uses: alexellis/arkade-get@master
        with:
          yq: latest

      - name: Checkout Helm Chart
        uses: actions/checkout@main
        with:
          repository: jomakori/gke_GitOps
          token: ${{ steps.doppler.outputs.GITHUB_TOKEN }}

      - name: Deploy Staging
        env:
          CONTAINER_TAG: ${{ steps.doppler.outputs.SEMANTIC_VERSION }} #retrieved from build step
          ENV_NUM: 0 # staging env
          GIT_MESSAGE: "deploy(notes-app): Test changes in: ${CONTAINER_TAG}"
        run: |
          # Login Git
          git config --global user.email $GH_USER_EMAIL
          git config --global user.name $GH_USER

          devbox run deploy

  comment-pr:
    name: Comment on PR
    environment: staging
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@main
        with:
          lfs: true

      - name: Comment on PR
        run: |
          PR_NUM=$(gh pr view --json number -q .number)
          gh pr comment $PR_NUM --repo "jomakori/demoapp" --body "$msg"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          msg: |
            ## `Staging` env deployed ✅
            - ### [Notes App API (backend)](https://staging-notes-app.intrc.net/)
            - ### [Notes App UI (frontend)](https://staging-flower.intrc.net/)

            ### Verify deployment by:
            - #### Confirming the version in ArgoCD
            - #### Confirming `rev` label in EKS pods/deployments = PR number

            ## 📄 Checklist before merging to PROD
            - [ ] Confirm Changes
            - [ ] Merge PR - to release changes to production.

            > [!IMPORTANT]
            > If there are changes that need to be made or merge conflicts you need to resolve, make the changes in feature branch, then merge branch to staging
              - Reason: The `staging` branch only allows changes that go thru the Merge Queue - hence need for new merge from feature branch
